import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowUpRight, Check, Copy, Download, Home, Mail, Volume2, VolumeX, Sparkles, MapPin, Github, Linkedin } from 'lucide-react';
import { channels, portfolio as p } from './content';

export function Preview({ type }: { type: string }) {
  return <div className={`preview preview-${type}`} aria-hidden="true">
    {type === 'about' && p.portrait ? <img className="channel-avatar" src={p.portrait} alt=""/> : type === 'about' && <><span className="hello-sticker">hello!</span><div className="portrait-art"><div className="hair"/><div className="face"><i/><i/><b/></div><div className="shirt"/></div><span className="little-star">✳</span></>}
    {type === 'projects' && <><div className="mini-window back-window"/><div className="mini-window"><div className="window-dots">•••</div><div className="window-picture"><i/><b/></div><div className="window-lines"/></div><span className="project-cursor">↖</span></>}
    {type === 'experience' && <><div className="tiny-timeline"><i/><i/><i/></div><span className="timeline-caption">one step at a time.</span></>}
    {type === 'resume' && <><div className="paper"><span>the story<br/>so far.</span><i/><i/><i/><b>↗</b></div><span className="paper-spark">✦</span></>}
    {type === 'playground' && <><div className="toy-ring"/><div className="toy-ball"/><div className="toy-cube"/><span className="toy-star">✳</span></>}
    {type === 'contact' && <><div className="envelope"><span>♡</span></div><span className="mail-bubble">let’s talk</span><span className="mail-star">✧</span></>}
  </div>;
}
function LinkOrUnavailable({ href, children }: { href: string | null; children: React.ReactNode }) {
  return href ? <a className="small-action" href={href} target="_blank" rel="noreferrer">{children}<ArrowUpRight size={18}/></a> : <span className="unavailable">{children} · not added yet</span>;
}
function Content({ section, project, go }: {section: string; project?: string; go: (path: string) => void}) {
  const [copied, setCopied] = useState(false);
  const [copyError, setCopyError] = useState(false);
  const [hue, setHue] = useState(205);
  const [playing, setPlaying] = useState(false);
  const copyTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  useEffect(() => () => { if (copyTimer.current) clearTimeout(copyTimer.current); }, []);
  const selected = p.projects.find(item => item.id === project);
  if (section === 'about') return <div className="about-layout"><div className="portrait-card">{p.portrait ? <img src={p.portrait} alt={p.name}/> : <><Preview type="about"/><span>Portrait placeholder</span></>}</div><div><p className="content-kicker">A HUMAN, FIRST.</p><h2>Hi, I’m {p.name}.</h2><p>{p.bio}</p><p className="location"><MapPin size={18}/>{p.location}</p><h3>Things I gravitate toward</h3><div className="tags">{p.interests.map(s => <span key={s}>{s}</span>)}</div><h3>My toolkit</h3><div className="tags blue">{p.skills.map(s => <span key={s}>{s}</span>)}</div></div></div>;
  if (section === 'projects') return selected ? <article className="project-detail"><button className="text-action" onClick={() => go('projects')}><ArrowLeft size={18}/>All projects</button><img className="project-hero" src={selected.image} alt={`${selected.title} sample interface illustration`}/><p className="content-kicker">SAMPLE PROJECT · {selected.category}</p><h2>{selected.title}</h2><p>{selected.detail}</p><div className="tags">{selected.technologies.map(t => <span key={t}>{t}</span>)}</div><div className="link-row"><LinkOrUnavailable href={selected.demo}>Live demo</LinkOrUnavailable><LinkOrUnavailable href={selected.source}>Source code</LinkOrUnavailable></div></article> : <><p className="content-kicker">SELECTED WORK · SAMPLE CONCEPTS</p><h2>Ideas, made real.</h2><p>A few things I’ve imagined, designed, and built. Replace these concepts with your own work.</p><div className="project-grid">{p.projects.map(item => <button className="project-card" key={item.id} onClick={() => go(`projects/${item.id}`)}><img src={item.image} alt={`${item.title} sample interface`}/><div><span>{item.category}</span><h3>{item.title}<ArrowUpRight size={23}/></h3><p>{item.description}</p></div></button>)}</div></>;
  if (section === 'experience') return <><p className="content-kicker">WORK, LEARNING & EVERYTHING BETWEEN</p><h2>A work in progress.</h2><p>Every chapter adds something. These entries are placeholders for your own journey.</p><ol className="experience-list">{p.experience.map(item => <li key={item.title}><span className="date">{item.date}</span><div><h3>{item.title}</h3><span className="organization">{item.organization}</span><p>{item.description}</p></div></li>)}</ol></>;
  if (section === 'resume') return <div className="resume-layout"><div><p className="content-kicker">THE SHORT VERSION</p><h2>On paper.</h2><p>{p.resumeSummary}</p><h3>{p.name}</h3><p>{p.role}</p><div className="tags">{p.skills.map(s => <span key={s}>{s}</span>)}</div><div className="download-block">{p.resume ? <a className="primary small" href={p.resume} download><Download size={19}/>Download résumé</a> : <><button className="primary small" disabled><Download size={19}/>Résumé coming soon</button><p>A résumé file hasn’t been added yet.</p></>}</div></div><div className="resume-sheet" aria-hidden="true"><span>{p.name}</span><small>{p.role}</small><hr/><b>PROFILE</b><i/><i/><i/><b>EXPERIENCE</b><i/><i/><i/><b>EDUCATION</b><i/><i/></div></div>;
  if (section === 'playground') return <><p className="content-kicker">NO BRIEF. JUST CURIOSITY.</p><h2>Room to play.</h2><p>Small ideas with nowhere to be. Try these two original interactive studies.</p><div className="experiment-grid"><article className="experiment"><div className="color-study" style={{background: `hsl(${hue} 45% 83%)`}}><div style={{background: `hsl(${(hue+65)%360} 55% 65%)`}}/><span>{hue}°</span></div><h3>{p.playground[0].title}</h3><p>{p.playground[0].description}</p><label>Change the color<input aria-label="Color radio hue" type="range" min="0" max="360" value={hue} onChange={e => setHue(Number(e.target.value))}/></label></article><article className="experiment"><div className={`orbit-study ${playing ? 'playing' : ''}`}><div><i/></div><b/></div><h3>{p.playground[1].title}</h3><p>{p.playground[1].description}</p><button className="small-action" aria-pressed={playing} onClick={() => setPlaying(!playing)}>{playing ? 'Pause orbit' : 'Play orbit'}</button></article></div></>;
  return <><p className="content-kicker">OPEN A NEW CONVERSATION</p><h2>Good things start<br/>with hello.</h2><p>Have an idea, a question, or just something nice to share?</p><div className="contact-email"><Mail size={27}/><span>{p.email || 'Your email goes here'}</span><button aria-label="Copy email" className="icon-button" disabled={!p.email} onClick={async () => {try { await navigator.clipboard.writeText(p.email!); setCopied(true); copyTimer.current = setTimeout(() => setCopied(false), 2500); } catch { setCopyError(true); }}}>{copied ? <Check/> : <Copy/>}</button></div><p className="copy-status" role="status">{copied ? 'Email copied to clipboard.' : copyError ? 'Copy is unavailable. Select the email address above to copy it.' : !p.email ? 'Contact details haven’t been added yet.' : 'Copy the address or send a note below.'}</p><div className="social-links"><LinkOrUnavailable href={p.email ? `mailto:${p.email}` : null}><Mail size={20}/>Email</LinkOrUnavailable><LinkOrUnavailable href={p.github}><Github size={20}/>GitHub</LinkOrUnavailable><LinkOrUnavailable href={p.linkedin}><Linkedin size={20}/>LinkedIn</LinkOrUnavailable></div></>;
}
export function Screen({ route, go, sound, toggleSound, active }: {route: string; go: (path: string) => void; sound: boolean; toggleSound: () => void; active: boolean}) {
  const [time, setTime] = useState(new Date());
  const [section, project] = route.split('/');
  const channel = channels.find(c => c.id === section);
  const lastSection = useRef('');
  const root = useRef<HTMLDivElement>(null);
  useEffect(() => {const timer = setInterval(() => setTime(new Date()), 30000); return () => clearInterval(timer);}, []);
  useEffect(() => {
    if (!active) return;
    const timer = setTimeout(() => {
      const target = channel ? root.current?.querySelector<HTMLElement>('.channel-heading') : root.current?.querySelector<HTMLElement>(`[data-channel="${lastSection.current || 'about'}"]`);
      target?.focus({preventScroll: true});
      root.current?.querySelector('.channel-body')?.scrollTo(0, 0);
      if (channel) lastSection.current = channel.id;
    }, 80);
    return () => clearTimeout(timer);
  }, [route, active, channel]);
  return <div ref={root} onWheelCapture={event => event.stopPropagation()} className={`tv-screen ${channel ? 'has-channel' : ''}`} inert={!active}>
    {channel ? <section className={`channel-content content-${section}`} key={route}><header className="channel-top"><button className="text-action" onClick={() => go('channels')}><ArrowLeft size={19}/>Back to channels</button><span>CH {channel.number}</span></header><div className="channel-body"><h1 className="channel-heading" tabIndex={-1}>{channel.name}</h1><Content section={section} project={project} go={go}/><p className="sample-note">Sample portfolio · Make this space your own.</p></div></section> : <><header className="screen-header"><div><span className="screen-wordmark">your little corner.</span><p>Pick a channel. Make yourself at home.</p></div><span className="live-badge"><i/>PERSONAL PORTFOLIO</span></header><nav className="channel-grid" aria-label="Portfolio channels">{channels.map(c => <button data-channel={c.id} className={`channel-tile tile-${c.id}`} key={c.id} onClick={() => go(c.id)} onKeyDown={e => { const keys = ['ArrowRight','ArrowLeft','ArrowDown','ArrowUp']; if (!keys.includes(e.key)) return; e.preventDefault(); const columns = window.innerWidth < 760 ? 2 : 3; const step = e.key === 'ArrowRight' ? 1 : e.key === 'ArrowLeft' ? -1 : e.key === 'ArrowDown' ? columns : -columns; root.current?.querySelector<HTMLElement>(`[data-channel="${channels[(channels.indexOf(c) + step + channels.length) % channels.length].id}"]`)?.focus(); }}><Preview type={c.id}/><span className="tile-label">{c.name}<span>↗</span></span></button>)}</nav><div className="screen-caption"><Sparkles size={16}/><span>Six channels. A few different sides of me.</span></div></>}
    <footer className="screen-footer"><button onClick={() => go('channels')} className="home-control"><Home size={23}/><span>Home</span></button><div className="screen-clock"><time>{time.toLocaleTimeString([], {hour:'2-digit', minute:'2-digit', hour12:false})}</time><span>{time.toLocaleDateString([], {month:'short', day:'numeric'})}</span></div><button className="sound-control" aria-label={sound ? 'Turn sound off' : 'Turn sound on'} aria-pressed={sound} onClick={toggleSound}>{sound ? <Volume2 size={24}/> : <VolumeX size={24}/>}<span>Sound {sound ? 'on' : 'off'}</span></button></footer>
  </div>;
}
